server:
  port: 8801
spring:
  profiles:
    active: dev
  application:
    name: system-server
  datasource:
    url: jdbc:mysql://192.168.0.121:3306/pra
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# mybatis
mybatis:
  mapper-locations:  classpath:mapping/*/*.xml
  type-aliases-package: com.prostate.*.entity
